#!/bin/bash

# Get cluster name
FILE=aerospike/clustername.txt
if [ -f "$FILE" ]; then
    cluster_name=`cat aerospike/clustername.txt`
else
    cluster_name=document-demo
fi

aerolab cluster stop -n ${cluster_name}
sleep 3
aerolab cluster stop -n countries
sleep 3
aerolab client stop -n trino
sleep 3
aerolab client stop -n jupyter